### ISSUE TITLE
Proposing package to Melpa

### ISSUE THREAD

**Issue by fgimenez** [hhamud/sway-mode#2]
Hi @hhamud thanks for your awesome work in this mode! :heart:

I was planning to create a recipe to make the package available in melpa https://github.com/melpa/melpa so that your package is easier to install with `package.el`. Would you be ok with that? I'd be happy to prepare the recipe and be the recipe maintainer, let me know wdyt. You can read more about how to contribute to melpa here https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org

Thanks!

**Comment by hhamud** [comment]
Hey @fgimenez.

Sure, you'll be able to do that.

I will add you as a contributor so that you can update any missing bits since I have not updated this package in awhile.

**Comment by fgimenez** [comment]
Awesome thanks! Will ping you when the PR is ready.

**Comment by fgimenez** [comment]
@hhamud btw, under which license do you want to release the package? It must be GPL-compatible https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses

**Comment by fgimenez** [comment]
Oh, I see that there's a reference in the package file, but we still need a LICENSE file in the repo, I'll push it.

**Comment by fgimenez** [comment]
I've proposed some changes here #3 please @hhamud take a look, there are some warnings when building the package but I think it should be ok https://github.com/hhamud/sway-mode/actions/runs/4336114150/jobs/7571177300#step:4:31

**Comment by hhamud** [comment]
> I've proposed some changes here #3 please @hhamud take a look, there are some warnings when building the package but I think it should be ok https://github.com/hhamud/sway-mode/actions/runs/4336114150/jobs/7571177300#step:4:31

Yeah I've taken a look at the PR and have approved and merged it into main
